name: Laravel CI
on:
  push:
    branches: [ main, staging ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-server
      - name: Install composer dependencies
        run: |
          make setup
          composer require --dev illuminate/testing
      - name: Run unit tests via PHPUnit
        run: make test
      - name: Show test coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          XDEBUG_MODE: coverage
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{ github.workspace }}/build/logs/clover.xml:clover
          debug: true
      - name: Check lint via PHP CodeSniffer
        run: make lint
